# Generated by Django 2.2 on 2019-04-03 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Search Partners', 'Search Partners'), ('Ideas', 'Ideas'), ('Jobs and side jobs', 'Jobs and side jobs')], max_length=1)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
