# Generated by Django 2.2 on 2019-04-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20190403_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('SEARCH', 'Search Partners'), ('IDEAS', 'Ideas'), ('JOBS', 'Jobs and side jobs')], max_length=100),
        ),
    ]
