# Generated by Django 2.2 on 2019-04-04 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20190403_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 4, 4, 10, 16, 36, 522683, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
