# Generated by Django 2.2 on 2019-04-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_auto_20190404_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='url',
        ),
        migrations.AddField(
            model_name='announcement',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
